name: Release
on:
  push:
    branches:
      - 'master'
  workflow_run:
    workflows:
      - ""
    branches:
      - "master"
    types:
      - "completed"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew publishAllPublicationsToSpringExtensionsRepository
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: true
